import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "../../packages/ui/src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-container": "#2563eb",
        surface: "#f9f9ff",
        background: "#f9f9ff",
        "tertiary-container": "#00759f",
        "surface-bright": "#f9f9ff",
        "on-tertiary-container": "#e1f2ff",
        "on-error-container": "#93000a",
        "on-background": "#161c26",
        "on-primary-fixed": "#00174b",
        "surface-tint": "#0053db",
        "on-primary": "#ffffff",
        "secondary-fixed": "#e2e2e6",
        "surface-dim": "#d4dae8",
        "surface-container-low": "#f0f3ff",
        "on-tertiary": "#ffffff",
        "surface-variant": "#dde2f1",
        "on-secondary-fixed-variant": "#45474a",
        "surface-container-high": "#e3e8f6",
        "error-container": "#ffdad6",
        "on-secondary-container": "#616266",
        "secondary-fixed-dim": "#c6c6ca",
        "outline-variant": "#c3c6d7",
        "tertiary-fixed": "#c4e7ff",
        "tertiary-fixed-dim": "#7bd0ff",
        "on-tertiary-fixed": "#001e2c",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#ebf1ff",
        primary: "#004ac6",
        "inverse-primary": "#b4c5ff",
        "on-secondary-fixed": "#1a1c1f",
        "on-primary-fixed-variant": "#003ea8",
        outline: "#737686",
        "surface-container": "#e8eefc",
        "primary-fixed-dim": "#b4c5ff",
        "on-secondary": "#ffffff",
        "on-surface": "#161c26",
        "on-primary-container": "#eeefff",
        "secondary-container": "#dfdfe3",
        "on-tertiary-fixed-variant": "#004c69",
        error: "#ba1a1a",
        "on-surface-variant": "#434655",
        "inverse-surface": "#2b313b",
        "primary-fixed": "#dbe1ff",
        tertiary: "#005b7c",
        "on-error": "#ffffff",
        "surface-container-highest": "#dde2f1",
        secondary: "#5d5e62",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-3xl": "6rem",
        "gutter-sm": "1rem",
        "space-lg": "1.5rem",
        "gutter-lg": "2rem",
        gutter: "1.5rem",
        "space-md": "1rem",
        "margin-lg": "5rem",
        "space-sm": "0.75rem",
        "space-xl": "2.5rem",
        "margin-sm": "1.25rem",
        margin: "2rem",
        "space-2xl": "4rem",
        "space-2xs": "0.25rem",
        "space-xs": "0.5rem",
      },
      fontFamily: {
        "body-sm": ["var(--font-inter)", "Inter", "sans-serif"],
        "code-inline": ["var(--font-inter)", "Inter", "monospace"],
        "headline-xl": ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "display-mobile": ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "body-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-sm": ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "body-xl": ["var(--font-inter)", "Inter", "sans-serif"],
        "label-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-lg": ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-lg-mobile": ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-xl-mobile": ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        display: ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "body-sm": ["13px", { lineHeight: "20px", letterSpacing: "0.005em", fontWeight: "400" }],
        "code-inline": ["13px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "500" }],
        "headline-xl": ["56px", { lineHeight: "64px", letterSpacing: "-0.035em", fontWeight: "700" }],
        "display-mobile": ["44px", { lineHeight: "50px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "body-md": ["15px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "body-xl": ["20px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "-0.005em", fontWeight: "500" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.03em", fontWeight: "600" }],
        "headline-md": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-lg": ["17px", { lineHeight: "28px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "headline-xl-mobile": ["36px", { lineHeight: "42px", letterSpacing: "-0.025em", fontWeight: "700" }],
        display: ["72px", { lineHeight: "80px", letterSpacing: "-0.04em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};

export default config;
